### ISSUE TITLE
Blend shapes don't import correctly

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#13]
### Issue description

Blend shapes import in-correctly.

### Steps to reproduce

1. Find a fbx with blend shapes.
2. Import with godot-ufbx
3. going from -1 to 1 blend shape values will scale the entire model

![image](https://github.com/V-Sekai/godot-ufbx/assets/32321/3057a02a-9832-4bf2-875d-b26d69cfe223)

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/e46cc52cce74310d14b8e77eb05e08944312a38c

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Macos, Godot 4.2 master.

**Comment by bqqbarbhg** [comment]
Blend shapes are severely broken currently as the mesh indexing is done independently for them, need to maintain some mapping from indexed vertices to the original ones, though that might cause issues if there are unique vertices in the exact same spot.

**Comment by fire** [comment]
Is this on ufbx or on Godot Engine?

**Comment by bqqbarbhg** [comment]
Neither, it's on the importer (and possibly the glTF importer in some edge cases, I haven't looked at it that close). Also like the comment mentions the glTF does not use relative blend shapes which is why I avoided them in the initial implementation as well. If they're supported these days should use them, but the indexing issue needs to be solved for those as well.
