### ISSUE TITLE
Wrong uvs on materials for the test model

### ISSUE THREAD

**Issue by fire** [V-Sekai/godot-ufbx#9]
### Issue description

![image](https://github.com/V-Sekai/godot-ufbx/assets/32321/8516a3c1-ef57-4e17-9094-5baa508ac76b)

The model materials look wrong.

![image](https://github.com/V-Sekai/godot-ufbx/assets/32321/4b4e07c6-474e-4611-8e0b-85e2d531d8a6)

### Steps to reproduce

Import with 

### Minimal reproduction project (For SDK or engine issues)

Load the fbx from 
https://sketchfab.com/3d-models/facial-body-animated-party-f-0001-actorcore-a676e4d13bea4ee6b6a2ba6201d5308b

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/ce2bd191ba89848ae1dc4f1cedf854846eda720b

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Macos, Godot 4.2 master. https://github.com/V-Sekai/godot/commit/5071f4ff70775e37247156e0274d48bca9bf2473

**Comment by fire** [comment]
@bqqbarbhg First bug report :)

**Comment by bqqbarbhg** [comment]
Looks like UVs are somehow messed up, also it's CC-BY which is perfect as I can add it to the ufbx public dataset!

**Comment by fire** [comment]
![image](https://github.com/V-Sekai/godot-ufbx/assets/32321/80315e23-2958-4196-98d3-e9741a7498ce)

Scaling by 1, -1 fixes this, but not sure it comes from.

**Comment by bqqbarbhg** [comment]
Yeah it's what I would have expected as well, could be mismatch in how Godot reads textures. Is there an adjust like that in the GLTF importer?

**Comment by fire** [comment]
Fixed by https://github.com/V-Sekai/godot-ufbx/commit/e46cc52cce74310d14b8e77eb05e08944312a38c

**Comment by bqqbarbhg** [comment]
Reopening this issue for a bit of discussion: Turns out the cause is that glTF specifies that the UV coordinate `(0,0)` maps to the top-left texture coordinate while FBX (and as far as I know most other formats) specify `(0,0)` as the _bottom-left_ coordinate.

The fix of flipping the Y scaling works for tiling textures, but for clamped textures it will map to negative texture Y coordinate values. It also does not fix the issue for user-provided materials and shaders that are not aware of the flipping.

It looks like the existing FBX2glTF solves the issue by calculating `1 - UV.y` for all UV coordinate planes by default:

https://github.com/godotengine/FBX2glTF/blob/bc05f0f8a6ff15963b8c1637b505e382303b248e/src/FBX2glTF.cpp#L268-L283

I would suggest doing the same here for consistency, user materials, and supporting multiple flipped UV planes. If we have support for import options could add one for flipping UVs that is enabled by default.

**Comment by fire** [comment]
I am divided between rebaking the material versus adjusting the uv scaling.

**Comment by bqqbarbhg** [comment]
End-users using the FBX meshes don't necessarily use the imported materials, but might use external materials and ones shared with glTF models, so I don't see a general solution that would work without modifying the mesh UV coordinate values.

**Comment by fire** [comment]
https://github.com/V-Sekai/godot-ufbx/commit/2f09dd6640442f031b00e3e7b01a15bbcfdefe93 How does this look?

**Comment by bqqbarbhg** [comment]
Looks great! There's still the extra UVs in the custom layers right below the diff, so might be good to do that for them as well for consistency.

**Comment by fire** [comment]
Godot supports 8 uvs. So it'll be good to do them for consistency.

**Comment by fire** [comment]
I split the 8uv issue into a different issue. https://github.com/V-Sekai/godot-ufbx/issues/18
